#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MockQMApp.Droid.Resource", IsApplication=true)]

namespace MockQMApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_qm = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_qm = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_qm = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_qm = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_qm = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_qm = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_cab_done_default_qm = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cab_done_focused_qm = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_pressed_qm = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_qm = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cab_background_bottom_qm = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cab_background_top_qm = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int diabetes = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int fortislogo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int heart = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int list_focused_qm = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int list_pressed_qm = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int menu = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int menu_dropdown_panel_qm = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int meradoctorlogo = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int password = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int progress_bg_qm = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int progress_horizontal_qm = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int progress_primary_qm = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int progress_secondary_qm = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int qmlogo = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int selectable_background_qm = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int spinner_ab_default_qm = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int spinner_ab_disabled_qm = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int spinner_ab_focused_qm = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int spinner_ab_pressed_qm = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int spinner_background_ab_qm = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int tab_indicator_ab_qm = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int tab_selected_focused_qm = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int tab_selected_pressed_qm = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int tab_selected_qm = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int tab_unselected_focused_qm = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int tab_unselected_pressed_qm = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int tab_unselected_qm = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int UserName = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ViewCellBackground = 2130837545;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f030001
			public const int ActionBar_Solid_Qm = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ActionBar_Transparent_Qm = 2130903042;
			
			// aapt resource value: 0x7f030005
			public const int ActionBarTabStyle_Qm = 2130903045;
			
			// aapt resource value: 0x7f030008
			public const int ActionButton_CloseMode_Qm = 2130903048;
			
			// aapt resource value: 0x7f030004
			public const int DropDownListView_Qm = 2130903044;
			
			// aapt resource value: 0x7f030006
			public const int DropDownNav_Qm = 2130903046;
			
			// aapt resource value: 0x7f030003
			public const int PopupMenu_Qm = 2130903043;
			
			// aapt resource value: 0x7f030007
			public const int ProgressBar_Qm = 2130903047;
			
			// aapt resource value: 0x7f030000
			public const int Theme_Qm = 2130903040;
			
			// aapt resource value: 0x7f030009
			public const int Theme_Qm_Widget = 2130903049;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
